// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArUJp9Rcc2U1kwoFH7eMKcx9cT31uCs9A',
    appId: '1:290246398032:web:e74a6f75ab76c0ea6ec155',
    messagingSenderId: '290246398032',
    projectId: 'gymcarnation',
    authDomain: 'gymcarnation.firebaseapp.com',
    storageBucket: 'gymcarnation.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARVoKOALcKS7G-j1rodQKn0CWdmD887WE',
    appId: '1:290246398032:android:88f781c40ef481c86ec155',
    messagingSenderId: '290246398032',
    projectId: 'gymcarnation',
    storageBucket: 'gymcarnation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrfDVkLXfuavQV80E82IIW_vXr8_vfIlA',
    appId: '1:290246398032:ios:03f7a3f88cc359ec6ec155',
    messagingSenderId: '290246398032',
    projectId: 'gymcarnation',
    storageBucket: 'gymcarnation.appspot.com',
    iosClientId: '290246398032-d1l6gu2203hqv092bi0l18fkghq8sboo.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymcarnation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrfDVkLXfuavQV80E82IIW_vXr8_vfIlA',
    appId: '1:290246398032:ios:8c544a6f3bc47c206ec155',
    messagingSenderId: '290246398032',
    projectId: 'gymcarnation',
    storageBucket: 'gymcarnation.appspot.com',
    iosClientId: '290246398032-rqarer83b98oh2bo3mgnvq7eejgktp00.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymcarnation.RunnerTests',
  );
}
